$font = Jetbrains Mono Bold

general {
    hide_cursor = true
    fractional_scaling = 2
}


animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = 
    path = ~/Wallpapers/leaves-hard-pixelated.png
    blur_passes = 0
    #vibracy = 0.5
}

input-field {
    monitor =
    size = 100 ,50
    outline_thickness = 5
    inner_color = rgba(0, 0, 0,100) # no fill
    

    font_color = rgb(251, 241, 199)
    fade_on_empty = false
    rounding = 50

    font_family = $font
    placeholder_text = PIN
    fail_text = Nuh.Uh

    fail_color = rgba(201,36,29,100)
    check_color = rgba(124, 111, 100,100)

    dots_text_format = *
    dots_size = 0.2
    dots_spacing = 0.2
    
    position = 0, -30
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 
    font_size = 75
    font_family = $font
    color= rgba(235, 219, 182, 100)
    position = 0, +100
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%d %B %Y" 
    font_size = 20
    font_family = $font
    color = rgba(235, 219, 182,100)
    position = 0, +30
    halign = center
    valign = center
}
# BATTERY
label {
    monitor =
    text = cmd[update:10000] ~/Documents/Scripts/Battery.sh
    font_size = 20
    font_family = $font
    color = rgba(168, 153, 132,100)
    positon = 0, 0 
    halign = right
    valign = bottom
} 
# Song
label{
  monitor = 
  text = cmd[update:10000] ~/Documents/Scripts/SongDetails.sh
  halign = bottom
  valign = bottom
  font_family = Jetbrains Mono Italic Bold
  font_size = 20
  color = rgba(251, 241, 199,100)
}
